package se.tap2.j2nbus;

/**
 * Created by antongravestam on 8/1/13.
 */
public class Templates {

    public static final String CPP_CLASS =
    "/*\n This file is auto generated by j2nbus' annotation processor, that's why it looks a little crazy. \n DO NOT EDIT! \n*/\n" +
    "#pragma once\n" +

    "#include \"j2nbus_protocol.h\"\n" +
    "#include <string>             \n" +
    "#include <vector>             \n" +
    "__$includes                   \n" +
    "                              \n" +
    "class __$simpleclassname {    \n" +

    "    public:                   \n" +

    "   __$declarations            \n" +

    "    static std::string getJavaClassName() {                  \n" +
    "        return getJavaClassNameS();                          \n" +
    "    }                                                        \n" +

    "    static std::string getJavaClassNameS() {                 \n" +
    "        return std::string(\"__$fullclassname\");    \n" +
    "    }                         \n" +

    "    int toBytes(char* __out) { \n" +
    "        int __size = 0;        \n" +

    "        __$serializations      \n" +

    "        return __size;         \n" +
    "    }                          \n" +

    "    int fromBytes(char* __in) {\n" +
    "        int __size = 0;        \n" +

    "        __$deserializations    \n" +

    "        return __size;         \n" +
    "    }                          \n" +

    "};                              \n";
}
